### ISSUE TITLE
在demo目录下，执行 `uliweb syncdb`，出现如下的错误

### ISSUE THREAD

**Issue by Rainboylvx** [zhangchunlin/uliweb-apijson#7]
```
Traceback (most recent call last):
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/utils/pyini.py", line 600, in read
    v = eval_value(value, self.env(), self[sec_name], self._encoding, self._import_env)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/utils/pyini.py", line 201, in eval_value
    result = eval(txt, dict(globals), dict(locals))
  File "<string>", line 4
    'uliweb.contrib.template'
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/utils/pyini.py", line 600, in read
    v = eval_value(value, self.env(), self[sec_name], self._encoding, self._import_env)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/utils/pyini.py", line 201, in eval_value
    result = eval(txt, dict(globals), dict(locals))
  File "<string>", line 4
    'uliweb.contrib.template'
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/bin/uliweb", line 33, in <module>
    sys.exit(load_entry_point('Uliweb3', 'console_scripts', 'uliweb')())
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/manage.py", line 1619, in main
    call()
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/manage.py", line 1616, in call
    execute_command_line(args or sys.argv, get_commands, 'uliweb', callback)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/core/commands.py", line 417, in execute_command_line
    m.execute(callback)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/core/commands.py", line 353, in execute
    self.do_command(args, global_options)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/core/commands.py", line 380, in do_command
    command = self.fetch_command(global_options, subcommand)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/core/commands.py", line 298, in fetch_command
    commands = self.get_commands(global_options)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/core/commands.py", line 273, in get_commands
    commands = self.commands(global_options)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/manage.py", line 44, in get_commands
    collect_commands()
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/manage.py", line 34, in collect_commands
    apps = get_apps(global_options.apps_dir, settings_file=global_options.settings,
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/core/SimpleFrame.py", line 497, in get_apps
    x = pyini.Ini(inifile, basepath=apps_dir)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/utils/pyini.py", line 442, in __init__
    self.read(self._inifile)
  File "/home/rainboy/__git__/PYHTON/uliweb-apijson/demo/src/uliweb3/uliweb/utils/pyini.py", line 603, in read
    raise Exception("Converting value (%s) error in %s:%d:%s" % (value, filename or self._inifile, lineno, line))
Exception: Converting value (
'uliweb.contrib.staticfiles'
'uliweb.contrib.template'
'uliweb.contrib.upload'
'uliweb.contrib.orm'
'uliweb.contrib.session'
'uliweb.contrib.cache'
'uliweb.contrib.auth'
'uliweb.contrib.i18n'
'uliweb.contrib.flashmessage'
'uliweb.contrib.rbac'
'uliweb_comui'
'uliweb_comapps.auth.login'
'uliweb_comapps.auth.user_admin'
'uliweb_apijson.apijson'
'apijson_demo'
'tables'
) error in /home/rainboy/__git__/PYHTON/uliweb-apijson/demo/apps/settings.ini:6:INSTALLED_APPS = [

```

**Comment by zhangchunlin** [comment]
settings.ini 里我原来的代码在各个app字符串之间是有逗号的，你的错误信息看起来怎么没有逗号？
https://github.com/zhangchunlin/uliweb-apijson/blob/master/demo/apps/settings.ini#L7

**Comment by claro5** [comment]
我也遇到这样的情况：
e:\Source\API\uliweb-apijosn\demo>uliweb syncdb
Traceback (most recent call last):
  File "d:\pyenv\py38\lib\site-packages\uliweb\utils\pyini.py", line 600, in read
    v = eval_value(value, self.env(), self[sec_name], self._encoding, self._import_env)
  File "d:\pyenv\py38\lib\site-packages\uliweb\utils\pyini.py", line 201, in eval_value
    result = eval(txt, dict(globals), dict(locals))
  File "<string>", line 4
    'uliweb.contrib.template'
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "d:\pyenv\py38\lib\site-packages\uliweb\utils\pyini.py", line 600, in read
    v = eval_value(value, self.env(), self[sec_name], self._encoding, self._import_env)
  File "d:\pyenv\py38\lib\site-packages\uliweb\utils\pyini.py", line 201, in eval_value
    result = eval(txt, dict(globals), dict(locals))
  File "<string>", line 4
    'uliweb.contrib.template'
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\PYENV\Py38\Scripts\uliweb.exe\__main__.py", line 7, in <module>
  File "d:\pyenv\py38\lib\site-packages\uliweb\manage.py", line 1619, in main
    call()
  File "d:\pyenv\py38\lib\site-packages\uliweb\manage.py", line 1616, in call
    execute_command_line(args or sys.argv, get_commands, 'uliweb', callback)
  File "d:\pyenv\py38\lib\site-packages\uliweb\core\commands.py", line 417, in execute_command_line
    m.execute(callback)
  File "d:\pyenv\py38\lib\site-packages\uliweb\core\commands.py", line 353, in execute
    self.do_command(args, global_options)
  File "d:\pyenv\py38\lib\site-packages\uliweb\core\commands.py", line 380, in do_command
    command = self.fetch_command(global_options, subcommand)
  File "d:\pyenv\py38\lib\site-packages\uliweb\core\commands.py", line 298, in fetch_command
    commands = self.get_commands(global_options)
  File "d:\pyenv\py38\lib\site-packages\uliweb\core\commands.py", line 273, in get_commands
    commands = self.commands(global_options)
  File "d:\pyenv\py38\lib\site-packages\uliweb\manage.py", line 44, in get_commands
    collect_commands()
  File "d:\pyenv\py38\lib\site-packages\uliweb\manage.py", line 34, in collect_commands
    apps = get_apps(global_options.apps_dir, settings_file=global_options.settings,
  File "d:\pyenv\py38\lib\site-packages\uliweb\core\SimpleFrame.py", line 497, in get_apps
    x = pyini.Ini(inifile, basepath=apps_dir)
  File "d:\pyenv\py38\lib\site-packages\uliweb\utils\pyini.py", line 442, in __init__
    self.read(self._inifile)
  File "d:\pyenv\py38\lib\site-packages\uliweb\utils\pyini.py", line 603, in read
    raise Exception("Converting value (%s) error in %s:%d:%s" % (value, filename or self._inifile, lineno, line))
Exception: Converting value (
'uliweb.contrib.staticfiles'
'uliweb.contrib.template'
'uliweb.contrib.upload'
'uliweb.contrib.orm'
'uliweb.contrib.session'
'uliweb.contrib.cache'
'uliweb.contrib.auth'
'uliweb.contrib.i18n'
'uliweb.contrib.flashmessage'
'uliweb.contrib.rbac'
'uliweb_comui'
'uliweb_comapps.auth.login'
'uliweb_comapps.auth.user_admin'
'uliweb_apijson.apijson'
'apijson_demo'
'tables'
) error in e:\Source\API\uliweb-apijosn\demo\apps\settings.ini:6:INSTALLED_APPS
= [

**Comment by zhangchunlin** [comment]
@claro5 我之前用的是 py3.6 py3.7 ,3.8还没测试过，之后会测试下，你用3.7的先试试看？

**Comment by zhangchunlin** [comment]
确实是py3.8下的uliweb的问题，我有空会尝试修复一下。
@Rainboylvx  @claro5 你们先用 py3.7尝试吧

**Comment by zhangchunlin** [comment]
uliweb3上已经修复了这个问题，可以使用最新的git版本：https://github.com/limodou/uliweb3
pip安装的uliweb3版本还有问题，要等作者后续发布版本。
